version: "3.9"

services:
  atms.admin.db:
    image: postgres:16
    container_name: atms.admin.db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssw0rd!
      POSTGRES_DB: atms_admin
    ports:
      - "5432:5432"
    volumes:
      - atms.admin.db.data:/var/lib/postgresql/data
    restart: unless-stopped


  atms.project.db:
    image: postgres:16
    container_name: atms.project.db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssw0rd!
      POSTGRES_DB: atms_project
    ports:
      - "5434:5432"
    volumes:
      - atms.project.db.data:/var/lib/postgresql/data
    restart: unless-stopped
    
  atms.rabbitmq:
    image: rabbitmq:3.13-management
    container_name: atms.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: p@ssw0rd!
      RABBITMQ_DEFAULT_VHOST: atms
    ports:
      - "5672:5672"    # AMQP protocol (для микросервисов)
      - "15672:15672"  # Management UI (http://localhost:15672)
    volumes:
      - atms.rabbitmq.data:/var/lib/rabbitmq
    restart: unless-stopped



volumes:
  atms.admin.db.data:
  atms.project.db.data:
  atms.rabbitmq.data: