<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ATMS.Shared\ATMS.Application.Dispatcher\ATMS.Application.Dispatcher.csproj" />
      <ProjectReference Include="..\..\ATMS.Shared\ATMS.Caching\ATMS.Caching.csproj" />
      <ProjectReference Include="..\..\ATMS.Shared\ATMS.Email\ATMS.Email.csproj" />
	</ItemGroup>

	<ItemGroup>
      <ProjectReference Include="..\..\ATMS.Shared\ATMS.Messaging\ATMS.Messaging.csproj" />
      <ProjectReference Include="..\ATMS.Project.Contracts\ATMS.Project.Contracts.csproj" />
      <ProjectReference Include="..\ATMS.Project.Data\ATMS.Project.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\OrganizationMessages.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>OrganizationMessages.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\OrganizationMessages.ru.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>OrganizationMessages.ru.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\OrganizationMessages.az.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>OrganizationMessages.az.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\OrganizationMessages.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>OrganizationMessages.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\OrganizationMessages.ru.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>OrganizationMessages.ru.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\OrganizationMessages.az.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>OrganizationMessages.az.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
