// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class AttachmentMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.AttachmentMessages",
        typeof(AttachmentMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string NotFound => Get(nameof(NotFound));
    internal static string AttachmentRequired => Get(nameof(AttachmentRequired));
    internal static string FileMissing => Get(nameof(FileMissing));
    internal static string FileRequired => Get(nameof(FileRequired));
    internal static string FileEmpty => Get(nameof(FileEmpty));
    internal static string FileTooLarge => Get(nameof(FileTooLarge));
    internal static string FileTypeUnsupported => Get(nameof(FileTypeUnsupported));
    internal static string FileContentMismatch => Get(nameof(FileContentMismatch));
    internal static string TooManyFiles => Get(nameof(TooManyFiles));
    internal static string NameRequired => Get(nameof(NameRequired));
    internal static string NameTooLong => Get(nameof(NameTooLong));
    internal static string NameInvalidCharacters => Get(nameof(NameInvalidCharacters));
    internal static string FilterRequired => Get(nameof(FilterRequired));
}
