// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class CommentMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.CommentMessages",
        typeof(CommentMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string TextRequired => Get(nameof(TextRequired));
    internal static string TextTooLong => Get(nameof(TextTooLong));
    internal static string EditOwnOnly => Get(nameof(EditOwnOnly));
    internal static string NotFound => Get(nameof(NotFound));
    internal static string CommentRequired => Get(nameof(CommentRequired));
}
