// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class DashboardMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.DashboardMessages",
        typeof(DashboardMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string PeriodUnsupported => Get(nameof(PeriodUnsupported));

    internal static string ProjectIdInvalid => Get(nameof(ProjectIdInvalid));
}
