// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class GlobalSearchMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.GlobalSearchMessages",
        typeof(GlobalSearchMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string QueryLength => Get(nameof(QueryLength));
    internal static string TakeOutOfRange => Get(nameof(TakeOutOfRange));
    internal static string ItemNotFound => Get(nameof(ItemNotFound));
    internal static string ItemRequired => Get(nameof(ItemRequired));
    internal static string ItemTypeUnsupported => Get(nameof(ItemTypeUnsupported));
}
