// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class NotificationMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.NotificationMessages",
        typeof(NotificationMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string NotFound => Get(nameof(NotFound));
    internal static string NotificationRequired => Get(nameof(NotificationRequired));
}
