// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class WorkTaskMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.WorkTaskMessages",
        typeof(WorkTaskMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string NotFound => Get(nameof(NotFound));
    internal static string ProjectRequired => Get(nameof(ProjectRequired));
    internal static string TaskRequired => Get(nameof(TaskRequired));
    internal static string TicketRequired => Get(nameof(TicketRequired));
    internal static string TicketNotFound => Get(nameof(TicketNotFound));
    internal static string ParentNotFound => Get(nameof(ParentNotFound));
    internal static string ParentIsSubtask => Get(nameof(ParentIsSubtask));
    internal static string ParentTicketMismatch => Get(nameof(ParentTicketMismatch));
    internal static string HasSubtasks => Get(nameof(HasSubtasks));
    internal static string ParentIsSelf => Get(nameof(ParentIsSelf));
    internal static string ParentHasSubtasks => Get(nameof(ParentHasSubtasks));
    internal static string TitleRequired => Get(nameof(TitleRequired));
    internal static string TitleTooLong => Get(nameof(TitleTooLong));
    internal static string DescriptionTooLong => Get(nameof(DescriptionTooLong));
    internal static string StatusRequired => Get(nameof(StatusRequired));
    internal static string StatusUnsupported => Get(nameof(StatusUnsupported));
    internal static string PriorityRequired => Get(nameof(PriorityRequired));
    internal static string PriorityUnsupported => Get(nameof(PriorityUnsupported));
    internal static string AssigneeNotFound => Get(nameof(AssigneeNotFound));
    internal static string AssigneeMustBeStaff => Get(nameof(AssigneeMustBeStaff));
    internal static string DeadlineOutOfRange => Get(nameof(DeadlineOutOfRange));
    internal static string HierarchyFilterConflict => Get(nameof(HierarchyFilterConflict));
}
