// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class WorkGroupMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.WorkGroupMessages",
        typeof(WorkGroupMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string NotFound => Get(nameof(NotFound));
    internal static string ParentGroupNotFound => Get(nameof(ParentGroupNotFound));
    internal static string GroupTitleAlreadyExists => Get(nameof(GroupTitleAlreadyExists));
    internal static string MilestoneTitleAlreadyExists => Get(nameof(MilestoneTitleAlreadyExists));
    internal static string GroupNotEmpty => Get(nameof(GroupNotEmpty));
    internal static string MilestoneNotEmpty => Get(nameof(MilestoneNotEmpty));

    internal static string DuplicateTitle(bool isMilestone) =>
        isMilestone ? MilestoneTitleAlreadyExists : GroupTitleAlreadyExists;
}
