// <auto-generated />
using System.Globalization;
using System.Resources;

namespace ATMS.Project.Services.Resources;

internal static class WorkTicketMessages
{
    private static readonly ResourceManager ResourceManager = new(
        "ATMS.Project.Services.Resources.WorkTicketMessages",
        typeof(WorkTicketMessages).Assembly);

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    internal static string NotFound => Get(nameof(NotFound));
    internal static string ProjectRequired => Get(nameof(ProjectRequired));
    internal static string TicketRequired => Get(nameof(TicketRequired));
    internal static string TitleRequired => Get(nameof(TitleRequired));
    internal static string TitleTooLong => Get(nameof(TitleTooLong));
    internal static string DescriptionTooLong => Get(nameof(DescriptionTooLong));
    internal static string MilestoneRequired => Get(nameof(MilestoneRequired));
    internal static string MilestoneNotFound => Get(nameof(MilestoneNotFound));
    internal static string TypeRequired => Get(nameof(TypeRequired));
    internal static string TypeUnsupported => Get(nameof(TypeUnsupported));
    internal static string StatusRequired => Get(nameof(StatusRequired));
    internal static string StatusUnsupported => Get(nameof(StatusUnsupported));
    internal static string PriorityRequired => Get(nameof(PriorityRequired));
    internal static string PriorityUnsupported => Get(nameof(PriorityUnsupported));
    internal static string AssigneeNotFound => Get(nameof(AssigneeNotFound));
    internal static string DeadlineOutOfRange => Get(nameof(DeadlineOutOfRange));
}
