<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ATMS.Application.Dispatcher\ATMS.Application.Dispatcher.csproj" />
      <ProjectReference Include="..\ATMS.Application\ATMS.Application.csproj" />
      <ProjectReference Include="..\ATMS.Infrastructure\ATMS.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.0" />
    </ItemGroup>

</Project>
