<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\ATMS.Application.Dispatcher\ATMS.Application.Dispatcher.csproj" />
      <ProjectReference Include="..\ATMS.Application\ATMS.Application.csproj" />
      <ProjectReference Include="..\ATMS.Infrastructure\ATMS.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

</Project>
