<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ATMS.Email.Services</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentEmail.Razor" Version="3.0.2" />
      <PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ATMS.Infrastructure\ATMS.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="Templates\InviteTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
