<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ATMS.Email</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentEmail.Razor" />
      <PackageReference Include="FluentEmail.Smtp" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ATMS.Infrastructure\ATMS.Infrastructure.csproj" />
    </ItemGroup>
	
    <ItemGroup>
      <None Remove="Templates\InviteTemplate.cshtml" />
      <Content Include="Templates\InviteTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Templates\ForgotPasswordTemplate.cshtml" />
      <Content Include="Templates\ForgotPasswordTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Templates\TaskAssignedTemplate.cshtml" />
      <Content Include="Templates\TaskAssignedTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Templates\MentionedTemplate.cshtml" />
      <Content Include="Templates\MentionedTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Templates\DueTodayTemplate.cshtml" />
      <Content Include="Templates\DueTodayTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Templates\TaskOverdueTemplate.cshtml" />
      <Content Include="Templates\TaskOverdueTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Templates\AddedToProjectTemplate.cshtml" />
      <Content Include="Templates\AddedToProjectTemplate.cshtml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
