//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMS.Application.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATMS.Application.Exceptions.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must me less than {0} symbols..
        /// </summary>
        public static string DescriptionShouldBeLessThan {
            get {
                return ResourceManager.GetString("DescriptionShouldBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is required..
        /// </summary>
        public static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Image file is empty..
        /// </summary>
        public static string ImageEmpty {
            get {
                return ResourceManager.GetString("ImageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file is too large. Please upload an image up to 5 MB..
        /// </summary>
        public static string ImageTooLarge {
            get {
                return ResourceManager.GetString("ImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format is not supported. Use JPG, PNG, JFIF or WEBP..
        /// </summary>
        public static string ImageUnsupportedFormat {
            get {
                return ResourceManager.GetString("ImageUnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email (e.g. user@example.com)..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must me less than {0} symbols..
        /// </summary>
        public static string NameShouldBeLessThan {
            get {
                return ResourceManager.GetString("NameShouldBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID is required..
        /// </summary>
        public static string RoleIdRequired {
            get {
                return ResourceManager.GetString("RoleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title already exists ..
        /// </summary>
        public static string TitleAlreadyExists {
            get {
                return ResourceManager.GetString("TitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must me less than {0} symbols..
        /// </summary>
        public static string TitleShouldBeLessThan {
            get {
                return ResourceManager.GetString("TitleShouldBeLessThan", resourceCulture);
            }
        }

        public static string PageMustBePositive => ResourceManager.GetString("PageMustBePositive", resourceCulture);
        public static string PageSizeOutOfRange => ResourceManager.GetString("PageSizeOutOfRange", resourceCulture);
        public static string InvalidSortDirection => ResourceManager.GetString("InvalidSortDirection", resourceCulture);
        public static string InvalidCursor => ResourceManager.GetString("InvalidCursor", resourceCulture);
        public static string DateOutOfRange => ResourceManager.GetString("DateOutOfRange", resourceCulture);
        public static string InvalidDateRange => ResourceManager.GetString("InvalidDateRange", resourceCulture);
    }
}
