// <auto-generated />
using System;
using ATMS.Project.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ATMS.Project.Data.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20270411191808_SeedPermissionDataToTables")]
    partial class SeedPermissionDataToTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.PermissionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId", "Language")
                        .IsUnique();

                    b.ToTable("PermissionTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProjectKinds");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectKindTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProjectKindId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectKindId", "Language")
                        .IsUnique();

                    b.ToTable("ProjectKindTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProjectStatuses");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectStatusTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProjectStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectStatusId", "Language")
                        .IsUnique();

                    b.ToTable("ProjectStatusTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTypeId", "Language")
                        .IsUnique();

                    b.ToTable("ProjectTypeTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkGroupStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkGroupStatuses");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkGroupStatusTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkGroupStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkGroupStatusId", "Language")
                        .IsUnique();

                    b.ToTable("WorkGroupStatusTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkItemPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkItemPriorities");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkItemPriorityTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkItemPriorityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemPriorityId", "Language")
                        .IsUnique();

                    b.ToTable("WorkItemPriorityTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkTaskStatuses");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTaskStatusTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkTaskStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskStatusId", "Language")
                        .IsUnique();

                    b.ToTable("WorkTaskStatusTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkTicketStatuses");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketStatusTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkTicketStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkTicketStatusId", "Language")
                        .IsUnique();

                    b.ToTable("WorkTicketStatusTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkTicketTypes");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkTicketTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkTicketTypeId", "Language")
                        .IsUnique();

                    b.ToTable("WorkTicketTypeTranslations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("logo path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Voen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("Voen")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ParentWorkGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentWorkGroupId");

                    b.HasIndex("StatusId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("WorkProjectId", "ParentWorkGroupId", "Title")
                        .IsUnique();

                    b.ToTable("WorkGroups", t =>
                        {
                            t.HasCheckConstraint("CK_WorkGroup_Level", "\"Level\" <= 1");
                        });
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProjectKindId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("ProjectStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("ProjectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProjectKindId");

                    b.HasIndex("ProjectStatusId");

                    b.HasIndex("ProjectTypeId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Title")
                        .IsUnique();

                    b.ToTable("WorkProjects");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProjectParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkProjectParticipants");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProjectParticipantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkProjectParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkProjectParticipantId", "RoleId")
                        .IsUnique();

                    b.ToTable("WorkProjectParticipantRoles");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ParentWorkTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkTicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentWorkTaskId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkProjectId");

                    b.HasIndex("WorkTicketId");

                    b.ToTable("WorkTasks", t =>
                        {
                            t.HasCheckConstraint("CK_WorkTask_Level", "\"Level\" <= 1");
                        });
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkTicketStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("WorkTicketTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkGroupId");

                    b.HasIndex("WorkProjectId");

                    b.HasIndex("WorkTicketStatusId");

                    b.HasIndex("WorkTicketTypeId");

                    b.ToTable("WorkTickets");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.PermissionTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.Permission", "Permission")
                        .WithMany("Translations")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectKindTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.ProjectKind", "ProjectKind")
                        .WithMany("Translations")
                        .HasForeignKey("ProjectKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectKind");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectStatusTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.ProjectStatus", "ProjectStatus")
                        .WithMany("Translations")
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectStatus");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectTypeTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.ProjectType", "ProjectType")
                        .WithMany("Translations")
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkGroupStatusTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkGroupStatus", "WorkGroupStatus")
                        .WithMany("Translations")
                        .HasForeignKey("WorkGroupStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkGroupStatus");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkItemPriorityTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkItemPriority", "WorkItemPriority")
                        .WithMany("Translations")
                        .HasForeignKey("WorkItemPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItemPriority");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTaskStatusTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkTaskStatus", "WorkTaskStatus")
                        .WithMany("Translations")
                        .HasForeignKey("WorkTaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTaskStatus");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketStatusTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkTicketStatus", "WorkTicketStatus")
                        .WithMany("Translations")
                        .HasForeignKey("WorkTicketStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTicketStatus");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketTypeTranslation", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkTicketType", "WorkTicketType")
                        .WithMany("Translations")
                        .HasForeignKey("WorkTicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTicketType");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.User", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkGroup", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.WorkGroup", "ParentWorkGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentWorkGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkGroupStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.WorkProject", "WorkProject")
                        .WithMany("WorkGroups")
                        .HasForeignKey("WorkProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentWorkGroup");

                    b.Navigation("Status");

                    b.Navigation("WorkProject");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProject", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Organization", "Organization")
                        .WithMany("WorkProjects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.ProjectKind", "ProjectKind")
                        .WithMany()
                        .HasForeignKey("ProjectKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.ProjectStatus", "ProjectStatus")
                        .WithMany()
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("ProjectKind");

                    b.Navigation("ProjectStatus");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProjectParticipant", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.WorkProject", "WorkProject")
                        .WithMany("WorkProjectParticipants")
                        .HasForeignKey("WorkProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkProject");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProjectParticipantRole", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.Role", "Role")
                        .WithMany("WorkProjectParticipantRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.WorkProjectParticipant", "WorkProjectParticipant")
                        .WithMany("WorkProjectParticipantRoles")
                        .HasForeignKey("WorkProjectParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("WorkProjectParticipant");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkTask", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.WorkProjectParticipant", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ATMS.Project.Data.Entities.WorkTask", "ParentWorkTask")
                        .WithMany("Children")
                        .HasForeignKey("ParentWorkTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkItemPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkTaskStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.WorkProject", "WorkProject")
                        .WithMany()
                        .HasForeignKey("WorkProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.WorkTicket", "WorkTicket")
                        .WithMany("WorkTasks")
                        .HasForeignKey("WorkTicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("ParentWorkTask");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("WorkProject");

                    b.Navigation("WorkTicket");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkTicket", b =>
                {
                    b.HasOne("ATMS.Project.Data.Entities.WorkProjectParticipant", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkItemPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkTaskStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.WorkGroup", "WorkGroup")
                        .WithMany("WorkTickets")
                        .HasForeignKey("WorkGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.WorkProject", "WorkProject")
                        .WithMany()
                        .HasForeignKey("WorkProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkTicketStatus", "WorkTicketStatus")
                        .WithMany()
                        .HasForeignKey("WorkTicketStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Project.Data.Entities.Dictionaries.WorkTicketType", "WorkTicketType")
                        .WithMany()
                        .HasForeignKey("WorkTicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("WorkGroup");

                    b.Navigation("WorkProject");

                    b.Navigation("WorkTicketStatus");

                    b.Navigation("WorkTicketType");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectKind", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectStatus", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.ProjectType", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkGroupStatus", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkItemPriority", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTaskStatus", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketStatus", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Dictionaries.WorkTicketType", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Organization", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("WorkProjects");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("WorkProjectParticipantRoles");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("WorkTickets");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProject", b =>
                {
                    b.Navigation("WorkGroups");

                    b.Navigation("WorkProjectParticipants");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkProjectParticipant", b =>
                {
                    b.Navigation("WorkProjectParticipantRoles");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkTask", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ATMS.Project.Data.Entities.WorkTicket", b =>
                {
                    b.Navigation("WorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
