// <auto-generated />
using System;
using ATMS.Admin.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ATMS.Admin.Data.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260416160428_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NotSpecified"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Male"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Female"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Other"
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.GenderTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId", "Language")
                        .IsUnique();

                    b.ToTable("GenderTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenderId = 1,
                            Language = "en",
                            Name = "Not specified"
                        },
                        new
                        {
                            Id = 2,
                            GenderId = 1,
                            Language = "ru",
                            Name = "Не указано"
                        },
                        new
                        {
                            Id = 3,
                            GenderId = 1,
                            Language = "az",
                            Name = "Göstərilməyib"
                        },
                        new
                        {
                            Id = 4,
                            GenderId = 2,
                            Language = "en",
                            Name = "Male"
                        },
                        new
                        {
                            Id = 5,
                            GenderId = 2,
                            Language = "ru",
                            Name = "Мужской"
                        },
                        new
                        {
                            Id = 6,
                            GenderId = 2,
                            Language = "az",
                            Name = "Kişi"
                        },
                        new
                        {
                            Id = 7,
                            GenderId = 3,
                            Language = "en",
                            Name = "Female"
                        },
                        new
                        {
                            Id = 8,
                            GenderId = 3,
                            Language = "ru",
                            Name = "Женский"
                        },
                        new
                        {
                            Id = 9,
                            GenderId = 3,
                            Language = "az",
                            Name = "Qadın"
                        },
                        new
                        {
                            Id = 10,
                            GenderId = 4,
                            Language = "en",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 11,
                            GenderId = 4,
                            Language = "ru",
                            Name = "Другое"
                        },
                        new
                        {
                            Id = 12,
                            GenderId = 4,
                            Language = "az",
                            Name = "Digər"
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NotSpecified"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Single"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Married"
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.MaritalStatusTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaritalStatusId", "Language")
                        .IsUnique();

                    b.ToTable("MaritalStatusTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en",
                            MaritalStatusId = 1,
                            Name = "Not specified"
                        },
                        new
                        {
                            Id = 2,
                            Language = "ru",
                            MaritalStatusId = 1,
                            Name = "Не указано"
                        },
                        new
                        {
                            Id = 3,
                            Language = "az",
                            MaritalStatusId = 1,
                            Name = "Göstərilməyib"
                        },
                        new
                        {
                            Id = 4,
                            Language = "en",
                            MaritalStatusId = 2,
                            Name = "Single"
                        },
                        new
                        {
                            Id = 5,
                            Language = "ru",
                            MaritalStatusId = 2,
                            Name = "Холост"
                        },
                        new
                        {
                            Id = 6,
                            Language = "az",
                            MaritalStatusId = 2,
                            Name = "Subay"
                        },
                        new
                        {
                            Id = 7,
                            Language = "en",
                            MaritalStatusId = 3,
                            Name = "Married"
                        },
                        new
                        {
                            Id = 8,
                            Language = "ru",
                            MaritalStatusId = 3,
                            Name = "Женат"
                        },
                        new
                        {
                            Id = 9,
                            Language = "az",
                            MaritalStatusId = 3,
                            Name = "Evli"
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RoleView",
                            Module = "Role"
                        },
                        new
                        {
                            Id = 2,
                            Code = "RoleEdit",
                            Module = "Role"
                        },
                        new
                        {
                            Id = 3,
                            Code = "RoleDelete",
                            Module = "Role"
                        },
                        new
                        {
                            Id = 4,
                            Code = "UserView",
                            Module = "User"
                        },
                        new
                        {
                            Id = 5,
                            Code = "UserEdit",
                            Module = "User"
                        },
                        new
                        {
                            Id = 6,
                            Code = "UserDelete",
                            Module = "User"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ProjectView",
                            Module = "Project"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ProjectEdit",
                            Module = "Project"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ProjectDelete",
                            Module = "Project"
                        },
                        new
                        {
                            Id = 10,
                            Code = "NotificationView",
                            Module = "Notification"
                        },
                        new
                        {
                            Id = 11,
                            Code = "NotificationEdit",
                            Module = "Notification"
                        },
                        new
                        {
                            Id = 12,
                            Code = "NotificationDelete",
                            Module = "Notification"
                        },
                        new
                        {
                            Id = 13,
                            Code = "CommentView",
                            Module = "Comment"
                        },
                        new
                        {
                            Id = 14,
                            Code = "CommentEdit",
                            Module = "Comment"
                        },
                        new
                        {
                            Id = 15,
                            Code = "CommentDelete",
                            Module = "Comment"
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.PermissionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId", "Language")
                        .IsUnique();

                    b.ToTable("PermissionTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en",
                            Name = "Role View",
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Language = "ru",
                            Name = "Просмотр ролей",
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Language = "az",
                            Name = "Rola baxış",
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Language = "en",
                            Name = "Role edit",
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Language = "ru",
                            Name = "Редактирование ролей",
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Language = "az",
                            Name = "Rolu redaktə et",
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Language = "en",
                            Name = "Role delete",
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Language = "ru",
                            Name = "Удаление ролей",
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Language = "az",
                            Name = "Rolu sil",
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Language = "en",
                            Name = "User view",
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 11,
                            Language = "ru",
                            Name = "Просмотр пользователей",
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Language = "az",
                            Name = "İstifadəçiyə baxış",
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 13,
                            Language = "en",
                            Name = "User edit",
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 14,
                            Language = "ru",
                            Name = "Редактирование пользователей",
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 15,
                            Language = "az",
                            Name = "İstifadəçini redaktə",
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 16,
                            Language = "en",
                            Name = "User delete",
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 17,
                            Language = "ru",
                            Name = "Удаление пользователей",
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 18,
                            Language = "az",
                            Name = "İstifadəçini sil",
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 19,
                            Language = "en",
                            Name = "Project view",
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 20,
                            Language = "ru",
                            Name = "Просмотр проектов",
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 21,
                            Language = "az",
                            Name = "Layihəyə baxış",
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 22,
                            Language = "en",
                            Name = "Project edit",
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 23,
                            Language = "ru",
                            Name = "Редактирование проектов",
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 24,
                            Language = "az",
                            Name = "Layihəni redaktə",
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 25,
                            Language = "en",
                            Name = "Project delete",
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 26,
                            Language = "ru",
                            Name = "Удаление проектов",
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 27,
                            Language = "az",
                            Name = "Layihəni sil",
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 28,
                            Language = "en",
                            Name = "Comment view",
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 29,
                            Language = "ru",
                            Name = "Просмотр комментариев",
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 30,
                            Language = "az",
                            Name = "Şərhə baxış",
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 31,
                            Language = "en",
                            Name = "Comment edit",
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 32,
                            Language = "ru",
                            Name = "Редактирование комментариев",
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 33,
                            Language = "az",
                            Name = "Şərhi redaktə",
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 34,
                            Language = "en",
                            Name = "Comment delete",
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 35,
                            Language = "ru",
                            Name = "Удаление комментариев",
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 36,
                            Language = "az",
                            Name = "Şərhi sil",
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 37,
                            Language = "en",
                            Name = "Notification view",
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 38,
                            Language = "ru",
                            Name = "Просмотр уведомлений",
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 39,
                            Language = "az",
                            Name = "Bildirişə baxış",
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 40,
                            Language = "en",
                            Name = "Notification edit",
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 41,
                            Language = "ru",
                            Name = "Редактирование уведомлений",
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 42,
                            Language = "az",
                            Name = "Bildirişi redaktə",
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 43,
                            Language = "en",
                            Name = "Notification delete",
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 44,
                            Language = "ru",
                            Name = "Удаление уведомлений",
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 45,
                            Language = "az",
                            Name = "Bildirişi sil",
                            PermissionId = 12
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Locked"
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.UserStatusTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserStatusId", "Language")
                        .IsUnique();

                    b.ToTable("UserStatusTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en",
                            Name = "Active",
                            UserStatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Language = "ru",
                            Name = "Активный",
                            UserStatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            Language = "az",
                            Name = "Aktiv",
                            UserStatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            Language = "en",
                            Name = "Inactive",
                            UserStatusId = 2
                        },
                        new
                        {
                            Id = 5,
                            Language = "ru",
                            Name = "Неактивный",
                            UserStatusId = 2
                        },
                        new
                        {
                            Id = 6,
                            Language = "az",
                            Name = "Qeyri-aktiv",
                            UserStatusId = 2
                        },
                        new
                        {
                            Id = 7,
                            Language = "en",
                            Name = "Locked",
                            UserStatusId = 3
                        },
                        new
                        {
                            Id = 8,
                            Language = "ru",
                            Name = "Заблокирован",
                            UserStatusId = 3
                        },
                        new
                        {
                            Id = 9,
                            Language = "az",
                            Name = "Bloklanmış",
                            UserStatusId = 3
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5"),
                            Description = "Client Manager Role",
                            Name = "Client Manager"
                        },
                        new
                        {
                            Id = new Guid("dc91d07f-2a00-486b-8a90-aa7b4c688de8"),
                            Description = "Client Role",
                            Name = "Client"
                        },
                        new
                        {
                            Id = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53"),
                            Description = "Agent Role",
                            Name = "Agent"
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleId = new Guid("dc91d07f-2a00-486b-8a90-aa7b4c688de8")
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleId = new Guid("dc91d07f-2a00-486b-8a90-aa7b4c688de8")
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleId = new Guid("dc91d07f-2a00-486b-8a90-aa7b4c688de8")
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = new Guid("dc91d07f-2a00-486b-8a90-aa7b4c688de8")
                        },
                        new
                        {
                            PermissionId = 13,
                            RoleId = new Guid("dc91d07f-2a00-486b-8a90-aa7b4c688de8")
                        },
                        new
                        {
                            PermissionId = 1,
                            RoleId = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5")
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleId = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5")
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleId = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5")
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5")
                        },
                        new
                        {
                            PermissionId = 13,
                            RoleId = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5")
                        },
                        new
                        {
                            PermissionId = 14,
                            RoleId = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5")
                        },
                        new
                        {
                            PermissionId = 15,
                            RoleId = new Guid("4c0a7e27-0576-4738-9f73-1d9cc14374a5")
                        },
                        new
                        {
                            PermissionId = 1,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        },
                        new
                        {
                            PermissionId = 8,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        },
                        new
                        {
                            PermissionId = 13,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        },
                        new
                        {
                            PermissionId = 14,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        },
                        new
                        {
                            PermissionId = 15,
                            RoleId = new Guid("58a8f620-1550-41a2-8693-336fd9bbeb53")
                        });
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Tokens.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Tokens.RefreshRevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshRevokedTokens");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default-avatar.png");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long>("FailedLoginCount")
                        .HasColumnType("bigint");

                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("HasCompletedSurvey")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InvitedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaritalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("InvitedById");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserStatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.GenderTranslation", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.Gender", "Gender")
                        .WithMany("Translations")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.MaritalStatusTranslation", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.MaritalStatus", "MaritalStatus")
                        .WithMany("Translations")
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaritalStatus");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.PermissionTranslation", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.Permission", "Permission")
                        .WithMany("Translations")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.UserStatusTranslation", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.UserStatus", "UserStatus")
                        .WithMany("Translations")
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Admin.Data.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Tokens.PasswordResetToken", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Tokens.RefreshRevokedToken", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.User", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Admin.Data.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Admin.Data.Entities.Dictionaries.UserStatus", "UserStatus")
                        .WithMany()
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("InvitedBy");

                    b.Navigation("MaritalStatus");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.UserRole", b =>
                {
                    b.HasOne("ATMS.Admin.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMS.Admin.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.Gender", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.MaritalStatus", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Dictionaries.UserStatus", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ATMS.Admin.Data.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
