// <auto-generated />
using ATMS.Admin.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ATMS.Admin.Data.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260830071000_SystemProjectDeletePermissionRemoved")]
    partial class SystemProjectDeletePermissionRemoved
    {
    }
}
