<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />

		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="SixLabors.ImageSharp" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ATMS.Application.Exceptions\ATMS.Application.Exceptions.csproj" />
	</ItemGroup>
</Project>
