//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMS.Admin.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnboardingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnboardingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATMS.Admin.Service.Resources.OnboardingMessages", typeof(OnboardingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each email address can only be added once..
        /// </summary>
        public static string DuplicateInvitationEmail {
            get {
                return ResourceManager.GetString("DuplicateInvitationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid birth date..
        /// </summary>
        public static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid international phone number..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already registered or invited..
        /// </summary>
        public static string InvitationEmailInUse {
            get {
                return ResourceManager.GetString("InvitationEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can invite up to 6 colleagues..
        /// </summary>
        public static string InvitationLimit {
            get {
                return ResourceManager.GetString("InvitationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite colleagues or skip this step before finishing onboarding..
        /// </summary>
        public static string InvitationsIncomplete {
            get {
                return ResourceManager.GetString("InvitationsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations are only available to client managers..
        /// </summary>
        public static string InvitationsManagerOnly {
            get {
                return ResourceManager.GetString("InvitationsManagerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one colleague or skip this step..
        /// </summary>
        public static string InvitationsRequired {
            get {
                return ResourceManager.GetString("InvitationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least 18 years old..
        /// </summary>
        public static string MinimumAge {
            get {
                return ResourceManager.GetString("MinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your onboarding is already complete..
        /// </summary>
        public static string OnboardingAlreadyCompleted {
            get {
                return ResourceManager.GetString("OnboardingAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your onboarding was updated in another tab. Reload the page and try again..
        /// </summary>
        public static string OnboardingConcurrencyConflict {
            get {
                return ResourceManager.GetString("OnboardingConcurrencyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 10-40 characters with uppercase and lowercase letters, a number and a special character..
        /// </summary>
        public static string PasswordRequirements {
            get {
                return ResourceManager.GetString("PasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone number cannot exceed 20 characters..
        /// </summary>
        public static string PhoneNumberMaxLength {
            get {
                return ResourceManager.GetString("PhoneNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your personal information before finishing onboarding..
        /// </summary>
        public static string PersonalInfoIncomplete {
            get {
                return ResourceManager.GetString("PersonalInfoIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a profile photo..
        /// </summary>
        public static string ProfilePhotoRequired {
            get {
                return ResourceManager.GetString("ProfilePhotoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new password before finishing onboarding..
        /// </summary>
        public static string SecurityIncomplete {
            get {
                return ResourceManager.GetString("SecurityIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a supported gender..
        /// </summary>
        public static string UnsupportedGender {
            get {
                return ResourceManager.GetString("UnsupportedGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a supported language..
        /// </summary>
        public static string UnsupportedLanguage {
            get {
                return ResourceManager.GetString("UnsupportedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a supported marital status..
        /// </summary>
        public static string UnsupportedMaritalStatus {
            get {
                return ResourceManager.GetString("UnsupportedMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The onboarding version cannot be negative..
        /// </summary>
        public static string VersionInvalid {
            get {
                return ResourceManager.GetString("VersionInvalid", resourceCulture);
            }
        }
    }
}
