//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMS.Admin.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileMessages_az {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileMessages_az() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATMS.Admin.Service.Resources.ProfileMessages.az", typeof(ProfileMessages_az).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum tarixi gələcəkdə ola bilməz..
        /// </summary>
        internal static string BirthDateMaxValue {
            get {
                return ResourceManager.GetString("BirthDateMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum tarixi 1 yanvar 1900-dən əvvəl ola bilməz..
        /// </summary>
        internal static string BirthDateMinValue {
            get {
                return ResourceManager.GetString("BirthDateMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum tarixi sahəsi tələb olunur..
        /// </summary>
        internal static string BirthDateRequired {
            get {
                return ResourceManager.GetString("BirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi ən azı 18 yaşında olmalıdır..
        /// </summary>
        internal static string BirthDateValidValue {
            get {
                return ResourceManager.GetString("BirthDateValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum uzunluq {0} simvol olmalıdır..
        /// </summary>
        internal static string FileNameMaxLength {
            get {
                return ResourceManager.GetString("FileNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl adı tələb olunur..
        /// </summary>
        internal static string FileNameRequired {
            get {
                return ResourceManager.GetString("FileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil edilən cinsiyyət mövcud deyil..
        /// </summary>
        internal static string GenderNotSupported {
            get {
                return ResourceManager.GetString("GenderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyyət sahəsi tələb olunur..
        /// </summary>
        internal static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilin uzunluğu {0} simvol olmalıdır..
        /// </summary>
        internal static string LanguageLength {
            get {
                return ResourceManager.GetString("LanguageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil sahəsi tələb olunur..
        /// </summary>
        internal static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil edilən ailə vəziyyəti mövcud deyil..
        /// </summary>
        internal static string MaritalStatusNotSupported {
            get {
                return ResourceManager.GetString("MaritalStatusNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailə vəziyyəti sahəsi tələb olunur..
        /// </summary>
        internal static string MaritalStatusRequired {
            get {
                return ResourceManager.GetString("MaritalStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nömrəsi sahəsi tələb olunur..
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nömrəsi etibarlı deyil. Zəhmət olmasa ölkə kodunu daxil edin (məsələn, +994501234567)..
        /// </summary>
        internal static string PhoneNumberValidValue {
            get {
                return ResourceManager.GetString("PhoneNumberValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vəzifə {0} simvoldan artıq ola bilməz..
        /// </summary>
        internal static string PositionMaxLength {
            get {
                return ResourceManager.GetString("PositionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vəzifə sahəsi tələb olunur..
        /// </summary>
        internal static string PositionRequired {
            get {
                return ResourceManager.GetString("PositionRequired", resourceCulture);
            }
        }
    }
}
