<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ATMS.Shared\ATMS.Email\ATMS.Email.csproj" />
    <PackageReference Include="FluentEmail.Razor" />
  </ItemGroup>

</Project>
