<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ATMS.Shared\ATMS.Email\ATMS.Email.csproj" />
    <PackageReference Include="FluentEmail.Razor" Version="3.0.2" />
  </ItemGroup>

</Project>
