<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="AutoMapper" />
      <PackageReference Include="libphonenumber-csharp" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ATMS.Application\ATMS.Application.csproj" />
      <ProjectReference Include="..\ATMS.Contracts\ATMS.Contracts.csproj" />
      <ProjectReference Include="..\ATMS.Infrastructure\ATMS.Infrastructure.csproj" />
    </ItemGroup>

</Project>
